### ISSUE TITLE
isEmail should return false if the value passed is ""

### ISSUE THREAD

**Issue by eliassotodo** [NewOldMax/react-form-validator-core#34]
Hey there, since `""` is not a valid email, one would expect that `isEmail("")` return `false` instead of `true`.

**Comment by NewOldMax** [comment]
Hi,
if you want to validate empty values, you can use `required` validation or create your own.

Example: you have `optional` email field. If `isEmail("")` throws `false`, so you will not submit form, because `isEmail` requires some value and it's not a responsibility of `isEmail`, you just want to submit form with empty email field (because email not required)
