### ISSUE TITLE
isFormValid() issue

### ISSUE THREAD

**Issue by pavanshinde47** [NewOldMax/react-form-validator-core#41]
Hi @NewOldMax ,

Thanks for providing the isFormValid() method to get the form state if its valid or not.

I was trying to use it in the validatorListener but it keeps going into infinite loop. Where do you suggest we should use isFormValid() method?

**Comment by NewOldMax** [comment]
Hi,
here is an [example](https://codesandbox.io/s/m9zmwjq6qp) with `isFormValid` function. It disables submit button on invalid state case

**Comment by pavanshinde47** [comment]
In my form it showing false even if i fill all the required fields.

**Comment by pavanshinde47** [comment]
on onError isn't firing :(

**Comment by NewOldMax** [comment]
But it works in example. Maybe you have some issue in your form logic

**Comment by pavanshinde47** [comment]
Yeah, I didn't used validateListener, my bad.

**Comment by pavanshinde47** [comment]
this.setState({ isFormValid: this.form.isFormValid() }) this works in some cases and others it throws error
 Uncaught TypeError: _ValidationRules2.default[name] is not a function

**Comment by NewOldMax** [comment]
Can you reproduce it [here](https://codesandbox.io/s/m9zmwjq6qp)?

**Comment by pavanshinde47** [comment]
Hi @NewOldMax Can you check [this example](https://codesandbox.io/s/qvxp06z96q)

Here I have used PureComponent and `  handleError = () => {
    this.setState({ disabled: !this.form.isFormValid(false) });
  };`

When i type something, the pages becomes unresponsive, can you help me with why this  is happening.

**Comment by mike-strauch** [comment]
I think the problem in your [example](https://codesandbox.io/s/qvxp06z96q) is that you're using `handleError` as both the form `onError` handler and also the `validatorListener` on the field.  If you use `isFormValid()` instead of `isFormValid(false)` it seems to work ok.  

When you call `isFormValid(false)` that causes the validatorListener to be called on each field and since validatorListener is calling `isFormValid` you get into an infinite loop.  

I haven't seen that other error you mentioned (Uncaught TypeError: _ValidationRules2.default[name] is not a function) in your example after changing the `isFormValid(false)` to `isFormValid()`.

**Comment by NewOldMax** [comment]
Since `isFormValid` was changed, this issue is not acceptable anymore
